global using Motorcenter.Data.Contexts;
global using Microsoft.EntityFrameworkCore;
global using Motorcenter.API.DTO;
global using Motorcenter.Data;
global using AutoMapper;
global using Motorcenter.API.Extensions.Extensions;
global using Microsoft.EntityFrameworkCore.Internal;
global using Motorcenter.Data.Entities;
global using Motorcenter.Data.Services;